# This is a basic workflow to help you get started with Actions
# Protect the main branch: https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks
name: SageMaker Train

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  sm_train:
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1

    - name: Install requirements
      run: pip install --requirement requirements.txt
    
    - name: Fire SageMaker
      id: sm_train
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-2'   # optional: defaults to us-east-1
        AWS_DEFAULT_REGION: 'ap-northeast-2'
        PR_NUMBER: ${{ github.event.number }} # Only available for pr (no push)
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python sm_train.py

    
